/**
 * Docker Container Integration Tests
 *
 * These tests verify:
 * 1. Container creation with auto-generated names
 * 2. Container cleanup (pre-run and teardown)
 * 3. Port mapping and health checks
 * 4. Environment variable passing
 * 5. Context variable extraction from containers
 */

import { describe, it, expect, afterAll, beforeAll } from 'vitest';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);
const API_URL = process.env.API_URL || 'http://localhost:3000/api/v1';

interface TestNodeResult {
  nodeType: string;
  status: 'success' | 'error' | 'timeout';
  output: {
    containerId?: string;
    containerName?: string;
    containerNameAutoGenerated?: boolean;
    preRunCleanup?: {
      performed: boolean;
      containerRemoved: boolean;
    };
    exitCode?: number;
    stdout?: string;
    stderr?: string;
    host?: string;
    [key: string]: unknown;
  } | null;
  error?: string;
  duration: number;
  logs: Array<{ level: string; message: string; timestamp: string }>;
}

async function testNode(
  nodeType: string,
  config: Record<string, unknown>,
  inputs: Record<string, unknown> = {}
): Promise<TestNodeResult> {
  const response = await fetch(`${API_URL}/test/node`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ nodeType, config, inputs })
  });
  return response.json();
}

async function cleanupContainer(nameOrId: string): Promise<void> {
  try {
    await execAsync(`docker rm -f ${nameOrId} 2>/dev/null || true`);
  } catch {
    // Ignore cleanup errors
  }
}

async function isContainerRunning(nameOrId: string): Promise<boolean> {
  try {
    const { stdout } = await execAsync(`docker inspect --format='{{.State.Running}}' ${nameOrId} 2>/dev/null`);
    return stdout.trim() === 'true';
  } catch {
    return false;
  }
}

async function getRunningTestCraftContainers(): Promise<string[]> {
  try {
    const { stdout } = await execAsync(`docker ps --filter "name=testcraft-" --format "{{.Names}}" 2>/dev/null`);
    return stdout.trim().split('\n').filter(Boolean);
  } catch {
    return [];
  }
}

describe('Docker Container Integration', () => {
  // Clean up any leftover test containers before and after all tests
  beforeAll(async () => {
    const containers = await getRunningTestCraftContainers();
    for (const container of containers) {
      await cleanupContainer(container);
    }
  }, 30000);

  afterAll(async () => {
    const containers = await getRunningTestCraftContainers();
    for (const container of containers) {
      await cleanupContainer(container);
    }
  }, 30000);

  describe('Container Name Generation', () => {
    it('should auto-generate unique container name with random suffix', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        imageTag: 'latest',
        command: 'echo',
        args: ['hello'],
        removeAfterRun: true,
        detach: false
      });

      expect(result.status).toBe('success');
      expect(result.output?.containerName).toMatch(/^testcraft-alpine-[a-z0-9]{6}$/);
      expect(result.output?.containerNameAutoGenerated).toBe(true);
    }, 30000);

    it('should generate different names for consecutive runs', async () => {
      const result1 = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['run1'],
        removeAfterRun: true,
        detach: false
      });

      const result2 = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['run2'],
        removeAfterRun: true,
        detach: false
      });

      expect(result1.output?.containerName).not.toBe(result2.output?.containerName);
    }, 30000);

    it('should use user-specified container name', async () => {
      const customName = `test-custom-${Date.now()}`;

      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['custom'],
        name: customName,
        removeAfterRun: true,
        detach: false
      });

      expect(result.status).toBe('success');
      expect(result.output?.containerName).toBe(customName);
      expect(result.output?.containerNameAutoGenerated).toBe(false);
    }, 30000);
  });

  describe('Pre-Run Cleanup', () => {
    it('should perform pre-run cleanup when user specifies name', async () => {
      const containerName = `test-cleanup-${Date.now()}`;

      // First, create a container that will be left running
      const result1 = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'sleep',
        args: ['300'],
        name: containerName,
        detach: true
      });

      expect(result1.status).toBe('success');
      const isRunning = await isContainerRunning(containerName);
      expect(isRunning).toBe(true);

      // Now run again with same name - should cleanup first
      const result2 = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['replaced'],
        name: containerName,
        removeAfterRun: true,
        detach: false
      });

      expect(result2.status).toBe('success');
      expect(result2.output?.preRunCleanup?.performed).toBe(true);
      expect(result2.output?.preRunCleanup?.containerRemoved).toBe(true);

      // Cleanup
      await cleanupContainer(containerName);
    }, 60000);

    it('should report no cleanup needed when container does not exist', async () => {
      const containerName = `test-nonexistent-${Date.now()}`;

      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['first'],
        name: containerName,
        removeAfterRun: true,
        detach: false
      });

      expect(result.status).toBe('success');
      expect(result.output?.preRunCleanup?.performed).toBe(true);
      expect(result.output?.preRunCleanup?.containerRemoved).toBe(false);
    }, 30000);
  });

  describe('Detached Container Lifecycle', () => {
    it('should start container in detached mode and return container ID', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'sleep',
        args: ['60'],
        detach: true
      });

      expect(result.status).toBe('success');
      expect(result.output?.containerId).toBeDefined();
      expect(result.output?.containerId).toMatch(/^[a-f0-9]{64}$/);
      expect(result.output?.detached).toBe(true);

      // Verify container is actually running
      const isRunning = await isContainerRunning(result.output!.containerName!);
      expect(isRunning).toBe(true);

      // Cleanup
      await cleanupContainer(result.output!.containerName!);
    }, 30000);

    it('should stop detached container with docker-stop node', async () => {
      // Start a container
      const runResult = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'sleep',
        args: ['60'],
        detach: true
      });

      expect(runResult.status).toBe('success');
      const containerName = runResult.output!.containerName!;

      // Verify it's running
      expect(await isContainerRunning(containerName)).toBe(true);

      // Stop it
      const stopResult = await testNode('docker-stop', {
        containerName: containerName,
        remove: true
      });

      expect(stopResult.status).toBe('success');

      // Verify it's stopped
      expect(await isContainerRunning(containerName)).toBe(false);
    }, 60000);
  });

  describe('Port Mapping', () => {
    it('should expose ports correctly', async () => {
      const containerName = `test-ports-${Date.now()}`;

      const result = await testNode('docker-run', {
        imageName: 'nginx',
        imageTag: 'alpine',
        name: containerName,
        ports: [{ hostPort: 18080, containerPort: 80 }],
        detach: true
      });

      expect(result.status).toBe('success');
      expect(result.output?.port_80).toBe(18080);

      // Give nginx time to start
      await new Promise(r => setTimeout(r, 2000));

      // Try to connect to the mapped port
      try {
        const response = await fetch('http://localhost:18080');
        expect(response.status).toBe(200);
      } catch {
        // If fetch fails, that's also acceptable in test environment
      }

      // Cleanup
      await cleanupContainer(containerName);
    }, 60000);
  });

  describe('Environment Variables', () => {
    it('should pass environment variables to container', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'printenv',
        args: ['MY_VAR'],
        environment: {
          MY_VAR: 'test_value_123'
        },
        removeAfterRun: true,
        detach: false
      });

      expect(result.status).toBe('success');
      expect(result.output?.stdout?.trim()).toBe('test_value_123');
    }, 30000);

    it('should pass multiple environment variables', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'sh',
        args: ['-c', 'echo "$VAR1-$VAR2-$VAR3"'],
        environment: {
          VAR1: 'one',
          VAR2: 'two',
          VAR3: 'three'
        },
        removeAfterRun: true,
        detach: false
      });

      expect(result.status).toBe('success');
      expect(result.output?.stdout?.trim()).toBe('one-two-three');
    }, 30000);
  });

  describe('Database Container', () => {
    it('should auto-detect database image and run in detached mode', async () => {
      const result = await testNode('docker-run', {
        imageName: 'postgres',
        imageTag: '15-alpine',
        environment: {
          POSTGRES_PASSWORD: 'test123',
          POSTGRES_DB: 'testdb'
        },
        ports: [{ hostPort: 25432, containerPort: 5432 }],
        waitForHealthy: true,
        healthCheckTimeout: 30000
      });

      expect(result.status).toBe('success');
      expect(result.output?.detached).toBe(true); // Auto-detected as database
      expect(result.output?.port_5432).toBe(25432);
      expect(result.output?.host).toBe('localhost');

      // Cleanup
      if (result.output?.containerName) {
        await cleanupContainer(result.output.containerName);
      }
    }, 90000);
  });

  describe('Context Variable Extraction from Docker Output', () => {
    it('should extract container info for use in subsequent nodes', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'hostname',
        removeAfterRun: true,
        detach: false
      });

      expect(result.status).toBe('success');
      expect(result.output?.containerName).toBeDefined();
      expect(result.output?.host).toBe('localhost');

      // In a real test plan, these would be available as context variables:
      // - containerName: for cleanup
      // - host: for connecting to services
      // - port_XXXX: for port mappings
    }, 30000);
  });

  describe('Resource Limits', () => {
    it('should apply memory limits', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['memory limited'],
        memoryLimit: '64m',
        removeAfterRun: true,
        detach: false
      });

      // Memory limits may not work in all environments (WSL, some Docker configs)
      // Just verify the command doesn't crash
      expect(['success', 'error']).toContain(result.status);
    }, 30000);

    it('should apply CPU limits', async () => {
      const result = await testNode('docker-run', {
        imageName: 'alpine',
        command: 'echo',
        args: ['cpu limited'],
        cpuLimit: '0.5',
        removeAfterRun: true,
        detach: false
      });

      // CPU limits may not work in all environments
      expect(['success', 'error']).toContain(result.status);
    }, 30000);
  });
});

describe('Kubernetes Pod Integration', () => {
  // These tests require a running Kubernetes cluster
  // Skip if kubectl is not available or cluster is not reachable

  it.skip('should create and delete a Kubernetes pod', async () => {
    const result = await testNode('k8s-pod', {
      name: 'test-pod',
      namespace: 'default',
      image: 'nginx:alpine',
      waitForReady: true,
      timeout: 60000
    });

    expect(result.status).toBe('success');

    // Cleanup
    await testNode('k8s-pod', {
      name: 'test-pod',
      namespace: 'default',
      action: 'delete'
    });
  }, 120000);
});
